### ISSUE TITLE
Iterating over DB will causes double free crash when db is closed

### ISSUE THREAD

**Issue by jerryzhenleicai** [jerryzhenleicai/LevelDB.jl#14]
Julia version : Version 1.2.0-DEV.426 (2019-03-06)

[iterator_crash.jl.txt](https://github.com/jerryzhenleicai/LevelDB.jl/files/3408461/iterator_crash.jl.txt)

**Comment by jerryzhenleicai** [comment]
Run the attached testing code:


julia iterator_crash.jl
key is UInt8[0x0a], value is UInt8[0x01]
key is UInt8[0x0b, 0x0b], value is UInt8[0x02]
key is UInt8[0x0c, 0x0c], value is UInt8[0x03]
key is UInt8[0x0d], value is UInt8[0x04]
key is UInt8[0x0e], value is UInt8[0x05]
Closing DB

signal (11): Segmentation fault
in expression starting at /home/zcai/Dev/iterator_crash.jl:6
__libc_free at /build/glibc-OTsEL5/glibc-2.27/malloc/malloc.c:3123
jl_gc_free_array at /home/zcai/Dev/julia/src/gc.c:1005 [inlined]
sweep_malloced_arrays at /home/zcai/Dev/julia/src/gc.c:1026 [inlined]
gc_sweep_other at /home/zcai/Dev/julia/src/gc.c:1369 [inlined]
_jl_gc_collect at /home/zcai/Dev/julia/src/gc.c:2801
jl_gc_collect at /home/zcai/Dev/julia/src/gc.c:2874
jl_gc_pool_alloc at /home/zcai/Dev/julia/src/gc.c:1102
jl_gc_alloc_ at /home/zcai/Dev/julia/src/julia_internal.h:263 [inlined]
jl_gc_alloc at /home/zcai/Dev/julia/src/gc.c:2911
_new_array_ at /home/zcai/Dev/julia/src/array.c:100 [inlined]
_new_array at /home/zcai/Dev/julia/src/array.c:160 [inlined]
jl_alloc_array_1d at /home/zcai/Dev/julia/src/array.c:420
Type at ./boot.jl:401 [inlined]
Type at ./boot.jl:410 [inlined]
similar at ./abstractarray.jl:620 [inlined]
similar at ./abstractarray.jl:619 [inlined]
_array_for at ./array.jl:598 [inlined]
Type at ./compiler/inferencestate.jl:57
Type at ./compiler/inferencestate.jl:120
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:212
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:114
abstract_call at ./compiler/abstractinterpretation.jl:802
abstract_call at ./compiler/abstractinterpretation.jl:592
abstract_eval_call at ./compiler/abstractinterpretation.jl:831
abstract_eval at ./compiler/abstractinterpretation.jl:901
typeinf_local at ./compiler/abstractinterpretation.jl:1159
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1215
typeinf at ./compiler/typeinfer.jl:12
typeinf_ext at ./compiler/typeinfer.jl:586
typeinf_ext at ./compiler/typeinfer.jl:623
jfptr_typeinf_ext_1 at /home/zcai/Dev/julia/usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /home/zcai/Dev/julia/src/gf.c:2250

**Comment by jerryzhenleicai** [comment]
If I move the testing code into a standalone program (instead of @testset macro) then it's not crashing.

**Comment by jerryzhenleicai** [comment]
It seems to me that we need to set the own flag to False when we do the unsafe_wrap() call. That's because the value/key returned from the leveldb_iter_xxx call will be overwritten in memory once the iterator advance to the next position. See the comment here in the iterator.h in leveldb source:


  // Return the value for the current entry.  The underlying storage for
  // the returned slice is valid only until the next modification of
  // the iterator.
  // REQUIRES: Valid()
  virtual Slice value() const = 0;

**Comment by gdkrmr** [comment]
Good catch, i never noticed this probably because I haven't used iterators in my own code and the whole thing doesn't crash if you type it manually in the repl (until you trigger the garbage colector).

The solution is to copy the data. If leveldb changes the memory, we can never be sure about the actual contents. Do you know if this is only a problem with `leveldb_iter_key` and `leveldb_iter_value` or also with `leveldb_get`?

**Comment by gdkrmr** [comment]
if you confirm that this is fixed, I'll merge it.

**Comment by jerryzhenleicai** [comment]
I think leveldb_get does not have this problem.  At least I've used the set / get calls extensively and never had any problems.
